---
title: "679_seer"
author: "Danping Liu"
date: "4/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,readxl,tree,randomForest,caret)
```

```{r load_data}
transformed <- read_excel("Transformed.xlsx")
```

```{r sali}
sali <- transformed %>% filter(Site == "Salivary Gland")

sali <- sali %>% filter(`AJCC 7 Stage` != "IVC" & `AJCC 7 Stage` != "IVNOS")

sali$follow <- 0

saliB <- sali %>% filter(`AJCC 7 Stage` != "IVB")
unique(saliB$`Surgery Decision`)

for(i in 1:nrow(sali)){
  if (sali[i,]$`AJCC 7 Stage` != "IVB"){
     if(sali[i,]$`Surgery Decision` != "Not recommended"){
       sali[i,]$follow = 1
     }
  } else{
    if(sali[i,]$`Surgery Decision` == "Not recommended" | sali[i,]$`Surgery Decision` == "Not recommended, contraindicated due to              other cond; autopsy only (1973-2002)") {
      sali[i,]$follow == 1
    }
  }
}
```

```{r change_colname}
names(sali) <- gsub("\\s+", "_", names(sali))
names(sali) <- gsub("%_<", "Pct_Less_", names(sali))
names(sali) <- gsub("%_", "Pct_", names(sali))
names(sali) <- gsub("-", "_", names(sali))
names(sali) <- gsub("\\(|)", "", names(sali))
names(sali) <- gsub("\\?", "", names(sali))
sali$follow <- factor(sali$follow)
```

```{r get_sample_func}
getColUni <- function(x){
  length(unique(x))
} 
getSample <- function(data, pct){
  repeat{
    sample <-createDataPartition(y=data$follow,p=pct,list=FALSE)
    train <- data[sample,] 
    dataCat <- select_if(data,negate(is.numeric))
    trainCat <- select_if(train,negate(is.numeric))
    if(all(rapply(dataCat, getColUni)[-c(1,ncol(dataCat))]==rapply(trainCat, getColUni)[-c(1,ncol(trainCat))])) break
  }
  return(sample)
}
```

```{r test_sample}
sample <- getSample(sali, 0.7)
train <- sali[sample,]
test <- sali[-sample,]
length(train$follow==1)/length(train)
length(test$follow==1)/length(test)
length(train$follow)-sum(train$follow==1)
length(test$follow)-sum(test$follow==1)
sali_only_categorical_cols <- select_if(sali,negate(is.numeric))
train_only_categorical_cols <- select_if(train,negate(is.numeric))
sali_nuni <- sali_only_categorical_cols %>% summarise_all(n_distinct)
train_nuni <- train_only_categorical_cols %>% summarise_all(n_distinct)
sali_nuni == train_nuni
```

```{r random_forest}
rf_acc <- data.frame(matrix(ncol = 2, nrow = 23))
colnames(rf_acc) <- c("mtry_val","acc")
rf_acc$mtry_val <- 1:23
for(m in 1:23){
  rf <- randomForest(follow~.-Subsite-Surgery_Decision,data=train,mtry=m,importance=TRUE)
  rf_acc$acc[m] <- mean(predict(rf,newdata=test)==test$follow)
}
```