---
title: "EDA"
author: "Yu Zhe"
date: "2021/4/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
```

## R Markdown



```{r cars}
Health_Literacy_Transformed_Data <- read_excel("Health Literacy Transformed Data.xlsx", 
    sheet = "Transformed")
summary(Health_Literacy_Transformed_Data)
```

## Including Plots


```{r pressure,fig.width=10, fig.height=4}
#cause of death
ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`Cause of Death`,fill=Insurance),stat='count')+
  facet_grid(~Race)

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`Race`,fill=Insurance),stat='count')
```

```{r pressure,fig.width=15, fig.height=4}
#surgery decision
ggplot(data=Health_Literacy_Transformed_Data)+
  geom_histogram(mapping=aes(x=Insurance,fill=`Surgery Decision`),stat='count')+
  coord_flip()+
  facet_grid(~Race)
```
```{r pressure,fig.width=15, fig.height=4}
#Radiation
ggplot(data=Health_Literacy_Transformed_Data)+
  geom_histogram(mapping=aes(x=`Radiation`,fill=Insurance),stat='count')+
  coord_flip()+
  facet_grid(~Race)
```
```{r pressure}
#Chemotherapy
ggplot(data=Health_Literacy_Transformed_Data)+
  geom_histogram(mapping=aes(x=`Chemotherapy`,fill=Insurance),stat='count')+
  facet_grid(~Race)
```
```{r pressure,fig.width=12, fig.height=4}
#stage
ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`AJCC 7 Stage`,fill=`Surgery Decision`),stat='count')

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`AJCC 7 Stage`,fill=Chemotherapy),stat='count')

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`AJCC 7 Stage`,fill=Radiation),stat='count')
```


```{r pressure,fig.width=12, fig.height=4}
#stage
ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`Race`,fill=`Surgery Decision`),stat='count')

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`Race`,fill=Chemotherapy),stat='count')

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`Race`,fill=Radiation),stat='count')
```


```{r pressure,fig.width=12, fig.height=4}
#stage
ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`SEER Registry`,fill=`Surgery Decision`),stat='count')

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`SEER Registry`,fill=Chemotherapy),stat='count')

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`SEER Registry`,fill=Radiation),stat='count')
```


```{r pressure,fig.width=12, fig.height=4}
#stage
ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`Site`,fill=`Surgery Decision`),stat='count')

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`Site`,fill=Chemotherapy),stat='count')

ggplot(data=Health_Literacy_Transformed_Data)+geom_histogram(mapping=aes(x=`Site`,fill=Radiation),stat='count')
```

```{r}
library(psych)
library(vcd)
cor<-Health_Literacy_Transformed_Data[,2:25]
#poly_cor = polychoric(cor)
table <- xtabs(~Sex+`Age at Diagnosis`+Race+Insurance+`SEER Registry`+Site+Subsite+`AJCC 7 Stage`+Size+`Lymph Nodes`+Mets+`Cause of Death`+`Surgery Decision`+Radiation+Chemotherapy,data=cor )
assocstats(cor)
```



# Oral only

```{r}
oral <- filter(Health_Literacy_Transformed_Data,Site=='Oral Cavity' )
ggplot(data=oral)+geom_histogram(mapping=aes(x=`Surgery Performed?`,fill=`Surgery Decision`),stat='count')
```

```{r,fig.height=8}
ggplot(data=oral)+geom_histogram(mapping=aes(x=`Race`,fill=`Surgery Performed?`),stat='count')
ggplot(data=oral)+geom_histogram(mapping=aes(x=`Insurance`,fill=`Surgery Performed?`),stat='count')
```

```{r}
oral$follow <- ifelse(oral$`Surgery Performed?`=='Yes',1,0)
fit_oral <- glm(follow~Sex+Race+`SEER Registry`+Size+`AJCC 7 Stage`+Insurance+`Age at Diagnosis`+`% <9th Grade Education`+                     `% <High School Education`+`% <Bachelors Education`+`% Persons Below Poverty`+`% Unemployed ACS 2013-2017`+`Median Household Income`,
                oral,family=binomial(link='logit'))
summary(fit_oral)
```

```{r}
library(pROC)
#对测试集进行预测
pre_logistic<-as.numeric(predict(fit_oral,type="response")>0.5)
#将测试集计算所得概率与观测本身取值整合到一起
obs_p_logistic = data.frame(prob=pre_logistic,obs=oral$follow)
#输出混淆矩阵
table(obs=oral$follow,pre_logistic,dnn=c("真实值","预测值"))   
#绘制ROC曲线
logistic_roc <- roc(oral$follow,pre_logistic)
plot(logistic_roc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),grid.col=c("green", "red"), max.auc.polygon=TRUE,auc.polygon.col="skyblue", print.thres=TRUE,main='逻辑回归ROC曲线')
```

# Salivary Gland

```{r}
sali <- Health_Literacy_Transformed_Data %>% filter(Site == "Salivary Gland")

sali <- sali %>% filter(`AJCC 7 Stage` != "IVC" & `AJCC 7 Stage` != "IVNOS")

sali$follow <- 0

saliB <- sali %>% filter(`AJCC 7 Stage` != "IVB")
unique(saliB$`Surgery Decision`)

for(i in 1:nrow(sali)){
  if (sali[i,]$`AJCC 7 Stage` != "IVB"){
     if(sali[i,]$`Surgery Decision` != "Not recommended"){
       sali[i,]$follow = 1
     }
  } else{
    if(sali[i,]$`Surgery Decision` == "Not recommended" | sali[i,]$`Surgery Decision` == "Not recommended, contraindicated due to              other cond; autopsy only (1973-2002)") {
      sali[i,]$follow == 1
    }
  }
}

```

## Plot

```{r}
ggplot(data=sali)+geom_histogram(mapping=aes(x=`Race`,fill=`follow`),stat='count',position = 'dodge')
ggplot(data=sali)+geom_bar(mapping=aes(x=`Insurance`,fill=`follow`),stat='count',position = 'dodge')
```





```{r}
sali$follow <- as.factor(sali$follow)
ggplot(sali)+geom_histogram(aes(x=follow),stat="count")
2305-sum(sali$follow==1)
colnames(sali)
```

```{r}
library(caret)
trainsali <- sali[,-c(1,15,16,20:25)]
train <-createDataPartition(y=trainsali$follow,p=0.7,list=FALSE)
traindata <- trainsali[train, ] 
length(traindata$follow)-sum(traindata$follow==1)
testdata <- trainsali[-train, ]
length(testdata$follow)-sum(testdata$follow==1)
```

```{r}
getColUni <- function(x) length(unique(x))
getSample <- function(data){
  repeat{
    sample <- sample(1:nrow(data), round(nrow(data)*0.7), replace=FALSE)
    train <- data[sample,]
    if(all(rapply(data, getColUni)[-c(1,24)]==rapply(train, getColUni)[-c(1,24)])) break
  }
  return(sample)
}
```

```{r}
getColUni <- function(x){
  length(unique(x))
} 
getSample <- function(data){
  repeat{
    sample <-createDataPartition(y=data$follow,p=0.7,list=FALSE)
    train <- data[sample, ] 
    # length(train$follow)-sum(train$follow==1)
    # test <- data[-sample, ]
    # length(test$follow)-sum(test$follow==1)
    dataCat <- select_if(data,negate(is.numeric))
    trainCat <- select_if(train,negate(is.numeric))
    if(all(rapply(dataCat, getColUni)[-c(1,ncol(dataCat))]==rapply(trainCat, getColUni)[-c(1,ncol(trainCat))])) break
  }
  return(sample)
}

sample <- getSample(trainsali)
```

```{r}
traindata1 <- trainsali[sample, ] 
length(traindata1$follow)-sum(traindata1$follow==1)
testdata1 <- trainsali[-sample, ]
length(testdata1$follow)-sum(testdata1$follow==1)


write.csv(traindata1,"traindata1.csv",row.names = F)
write.csv(testdata1,"testdata1.csv",row.names = F)
```


## SVM

```{r}
library(pROC) #绘制ROC曲线
library(e1071)
svm <- svm(follow~.,traindata1,type='C',kernel='radial')
```

```{r}
#测试集
pre_svm <- predict(svm,newdata = testdata1)
obs_p_svm = data.frame(prob=pre_svm,obs=testdata1$follow)
###输出混淆矩阵
table(testdata1$follow,pre_svm,dnn=c("真实值","预测值"))
###绘制ROC曲线
svm_roc <- roc(testdata1$follow,as.numeric(pre_svm))
plot(svm_roc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),grid.col=c("green", "red"), max.auc.polygon=TRUE,auc.polygon.col="skyblue", print.thres=TRUE,main='SVM模型ROC曲线 kernel = radial')
```

```{r}
library(rpart)
tc <- rpart.control(minsplit=20,minbucket=20,maxdepth=10,xval=5,cp=0.005)
rpart.mod=rpart(follow ~.,data=traindata1,method="class",
                parms = list(prior = c(0.65,0.35), split = "gini"),
                control=tc)
summary(rpart.mod)
#1.3看变量重要性
rpart.mod$variable.importance
#cp是每次分割对应的复杂度系数
rpart.mod$cp
plotcp(rpart.mod)
```

```{r}
library(rpart.plot)
rpart.plot(rpart.mod,branch=1, extra=106, under=TRUE, faclen=0,
           cex=0.8, main="决策树")
```
```{r}
rpart.mod.pru<-prune(rpart.mod, cp= rpart.mod$cptable[which.min(rpart.mod$cptable[,"xerror"]),"CP"]) 
rpart.mod.pru$cp
library(rpart.plot)
rpart.plot(rpart.mod.pru,branch=1, extra=106, under=TRUE, faclen=0,
           cex=0.8, main="决策树")
```
```{r}
rpart.pred<-predict(rpart.mod.pru,testdata1)
pre<-ifelse(rpart.pred[,2]>0.5,1,0)
#测试集
###输出混淆矩阵
table(testdata1$follow,pre,dnn=c("真实值","预测值"))
###绘制ROC曲线
cart_roc <- roc(testdata1$follow,as.numeric(pre))
plot(cart_roc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),grid.col=c("green", "red"), max.auc.polygon=TRUE,auc.polygon.col="skyblue", print.thres=TRUE,main='SVM模型ROC曲线 kernel = radial')
```

### balance sample

```{r}
library(ROSE)
colnames(traindata1) <- c('Sex','Year_of_Diagosis','Age_at_Diagnosis','Race','Insurance','SEER_Registry','nineth_grade_education','High_school_education','Bachelors_education','Persons_Below_Poverty','Unemployed','median_household_income','language_isolation','AJCC_7_Stage','Size','LN','follow')
traindata1$Sex <- as.factor(traindata1$Sex)
traindata1$Race <- as.factor(traindata1$Race)
traindata1$Insurance <- as.factor(traindata1$Insurance)
traindata1$SEER_Registry <- as.factor(traindata1$SEER_Registry)
traindata1$AJCC_7_Stage <- as.factor(traindata1$AJCC_7_Stage)
traindata1$LN <- as.factor(traindata1$LN)
datarose <- ROSE(follow~.,traindata1,seed=1)$data
```

```{r}
tc <- rpart.control(minsplit=20,minbucket=20,maxdepth=10,xval=5,cp=0.005)
rpart.mod=rpart(follow ~.,data=datarose,method="class",
                parms = list(prior = c(0.65,0.35), split = "gini"),
                control=tc)
summary(rpart.mod)
#1.3看变量重要性
rpart.mod$variable.importance
#cp是每次分割对应的复杂度系数
rpart.mod$cp
plotcp(rpart.mod)
rpart.mod.pru<-prune(rpart.mod, cp= rpart.mod$cptable[which.min(rpart.mod$cptable[,"xerror"]),"CP"]) 
rpart.mod.pru$cp
library(rpart.plot)
rpart.plot(rpart.mod.pru,branch=1, extra=106, under=TRUE, faclen=0,
           cex=0.8, main="决策树")
```
```{r}
colnames(testdata1) <- c('Sex','Year_of_Diagosis','Age_at_Diagnosis','Race','Insurance','SEER_Registry','nineth_grade_education','High_school_education','Bachelors_education','Persons_Below_Poverty','Unemployed','median_household_income','language_isolation','AJCC_7_Stage','Size','LN','follow')
rpart.pred<-predict(rpart.mod.pru,testdata1)
pre<-ifelse(rpart.pred[,2]>0.5,1,0)
#测试集
###输出混淆矩阵
table(testdata1$follow,pre,dnn=c("真实值","预测值"))
###绘制ROC曲线
cart_roc <- roc(testdata1$follow,as.numeric(pre))
plot(cart_roc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),grid.col=c("green", "red"), max.auc.polygon=TRUE,auc.polygon.col="skyblue", print.thres=TRUE,main='cart模型ROC曲线')
```

