---
title: "EDA_679"
author: "Maggie Sha"
date: "4/14/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(caret)
library(ROSE)
library(randomForest)
library(tree)
library(ggplot2)
```


```{r}
#Data import
data <- read_excel("Health Literacy Transformed Data.xlsx", 
           sheet = "Transformed")

guide <- read_excel("NCCN Guidelines.xlsx")
```


```{r}
# survival
unique(data$Race)
# [1] "Hispanic"      "Asian or Pacific Islander"     "White"                        
# [4] "Black"        "American Indian/Alaska Native"

white <- data %>% filter(Race == "White")
other_race <- data %>% filter(Race != "White")

# this data in unbalanced in terms of race
nrow(white) #16209
nrow(other_race) # 7082

table1 <- data.frame(table(white$`Cause of Death`))
table2 <- data.frame(table(other_race$`Cause of Death`))

g1 <- ggplot(table1, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "White")

g2 <- ggplot(table2, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Other")

g1
g2
```

```{r}
# surgery
table3 <- data.frame(table(white$`Surgery Performed?`))
table4 <- data.frame(table(other_race$`Surgery Performed?`))

g3 <- ggplot(table3, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "White")

g4 <- ggplot(table4, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Other")

g3
g4

```

```{r}
# surgery decision

table5 <- data.frame(table(white$`Surgery Performed?`))
table6 <- data.frame(table(other_race$`Surgery Performed?`))

g5 <- ggplot(table4, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "White")

g6 <- ggplot(table5, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Other" )

g5
g6


```

```{r}
# radiation
table5 <- data.frame(table(white$Radiation))
table6 <- data.frame(table(other_race$Radiation))

g5 <- ggplot(table5, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "White")

g6 <- ggplot(table6, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Other" )

g5
g6
```

```{R}
black <- data %>% filter(Race == "Black")
asian <- data %>% filter(Race == "Asian or Pacific Islander")

table1 <- data.frame(table(white$`Cause of Death`))
table2 <- data.frame(table(black$`Cause of Death`))
table3 <- data.frame(table(asian$`Cause of Death`))

g1 <- ggplot(table1, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "White")

g2 <- ggplot(table2, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Black")

g3 <- ggplot(table3, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Asian")
g1
g2
g3
```



```{R}
table1 <- data.frame(table(white$`Surgery Performed?`))
table2 <- data.frame(table(black$`Surgery Performed?`))
table3 <- data.frame(table(asian$`Surgery Performed?`))

g1 <- ggplot(table1, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "White")

g2 <- ggplot(table2, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Black")

g3 <- ggplot(table3, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Asian")
g1
g2
g3
```


```{r}
table1 <- data.frame(table(white$`Surgery Decision`))
table2 <- data.frame(table(black$`Surgery Decision`))
table3 <- data.frame(table(asian$`Surgery Decision`))

g1 <- ggplot(table1, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "White")

g2 <- ggplot(table2, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Black")

g3 <- ggplot(table3, aes(x = Var1, y = Freq, fill = Var1)) +
        geom_bar(stat = "identity", width = 0.8, position = position_dodge(width = 0.9)) +
        geom_text(aes(label = Freq/sum(Freq)), vjust = 2, color= "black", size=3) + 
        theme(axis.text.x = element_text(angle = 20)) +
        labs(title = "Asian")
g1
g2
g3
```



```{r}
sali <- data %>% filter(Site == "Salivary Gland")

sali <- sali %>% filter(`AJCC 7 Stage` != "IVC" & `AJCC 7 Stage` != "IVNOS")

sali$follow <- 0

saliB <- sali %>% filter(`AJCC 7 Stage` != "IVB")
unique(saliB$`Surgery Decision`)

for(i in 1:nrow(sali)){
  if (sali[i,]$`AJCC 7 Stage` != "IVB"){
     if(sali[i,]$`Surgery Decision` != "Not recommended"){
       sali[i,]$follow = 1
     }
  } else{
    if(sali[i,]$`Surgery Decision` == "Not recommended" | sali[i,]$`Surgery Decision` == "Not recommended, contraindicated due to              other cond; autopsy only (1973-2002)") {
      sali[i,]$follow == 1
    }
  }
}



sali$Race2 <- ifelse(sali$Race == "White", "White", "Other")
```
```{r}
names(sali) <- gsub("\\s+", "_", names(sali))
names(sali) <- gsub("%_<", "Pct_Less_", names(sali))
names(sali) <- gsub("%_", "Pct_", names(sali))
names(sali) <- gsub("-", "_", names(sali))
names(sali) <- gsub("\\(|)", "", names(sali))
names(sali) <- gsub("\\?", "", names(sali))
```

```{r}
#surgery decision, performed, radiation,  chemo, Mets, subsite, ID.
trainsali <- sali[,-c(1,15,16,20:25)]
trainsali$follow <- as.factor(trainsali$follow)
trainsali$Sex <- as.factor(trainsali$Sex)
trainsali$Year_of_Diagnosis <- as.factor(trainsali$Year_of_Diagnosis)
trainsali$Race <- as.factor(trainsali$Race)
trainsali$Insurance <- as.factor(trainsali$Insurance)
trainsali$AJCC_7_Stage <- as.factor(trainsali$AJCC_7_Stage )
trainsali$SEER_Registry <- as.factor(trainsali$SEER_Registry)

set.seed(123)
getColUni <- function(x){
  length(unique(x))
} 
getSample <- function(data){
  repeat{
    sample <-createDataPartition(y=data$follow,p=0.7,list=FALSE)
    train <- data[sample, ] 
    # length(train$follow)-sum(train$follow==1)
    # test <- data[-sample, ]
    # length(test$follow)-sum(test$follow==1)
    dataCat <- select_if(data,negate(is.numeric))
    trainCat <- select_if(train,negate(is.numeric))
    if(all(rapply(dataCat, getColUni)[-c(1,ncol(dataCat))]== rapply(trainCat, getColUni)[-c(1,ncol(trainCat))])) break
  }
  return(sample)
}

sample <- getSample(trainsali)

train <- trainsali[sample,]
test <- trainsali[-sample,]
```
```{r}
#tune: mtry, ntree, sampsize


rf = randomForest(follow ~ Sex + Race + Year_of_Diagnosis + Age_at_Diagnosis + Insurance + SEER_Registry + AJCC_7_Stage,
                   data = train, ntree=1000)
pred_forest = predict(rf, test, type = "class")
confusionMatrix(pred_forest, test$follow)
roc.curve(test$follow, factor(pred_forest))



# random forest with stratified sampling
rf2 = randomForest(follow ~ Year_of_Diagnosis + Race2 + Age_at_Diagnosis + Insurance + SEER_Registry + AJCC_7_Stage,
                   data = train, ntree=1000, sampsize=c(85,85),strata=train$follow)
pred_forest2 = predict(rf2, test, type = "class")
confusionMatrix(pred_forest2, test$follow)
roc.curve(test$follow, factor(pred_forest2))

# mccr(test$follow, pred_forest)
# F1_Score(test$follow, pred_forest)
```


```{r}
# glm logistic regression

library(MLmetrics)
library(mccr)

f1 <- glm(follow ~ Sex + Race2 + Year_of_Diagnosis + Age_at_Diagnosis + Insurance + SEER_Registry + AJCC_7_Stage, data = train, family = binomial)

summary(f1)

pred <- predict(f1, test)
roc.curve(test$follow, pred)
pred <- ifelse(pred > 0.5, 1, 0)
table(pred, test$follow)




data_balanced_over <- ovun.sample(follow ~ ., data = train, method = "both", p =0.5)$data
table(data_balanced_over$follow)

f2 <- glm(follow ~ Sex + Race2 + Year_of_Diagnosis + Age_at_Diagnosis + Insurance + SEER_Registry + AJCC_7_Stage, data = data_balanced_over, family = binomial)

summary(f1)

pred2 <- predict(f2, test)
roc.curve(test$follow, pred2)
pred2 <- ifelse(pred2 > 0.5, 1, 0)
table(pred2, test$follow)
```

```{r}
#glmer multilevel logistic regression
library(lme4)

multi <- glmer(follow ~ Sex + Race + Year_of_Diagnosis + Age_at_Diagnosis + Insurance  + AJCC_7_Stage + (1|SEER_Registry), data = train, family = binomial)

pred = predict(multi, test)

logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}

pred2 <- logit2prob(pred)
pred2 <- ifelse(pred2 > 0.5, 1, 0)
table(pred2, test$follow)
roc.curve(test$follow, pred)



data_balanced_over <- ovun.sample(follow ~ ., data = train, method = "both", p = 0.5)$data
table(data_balanced_over$follow)

multi <- glmer(follow ~ Sex + Race + Year_of_Diagnosis + Age_at_Diagnosis + Insurance  + AJCC_7_Stage + (1|SEER_Registry), data = data_balanced_over, family = binomial)

summary(multi)
pred = predict(multi, test)
roc.curve(test$follow, pred)
```

```{r}
#classification tree and pruned tree
tree1 <- tree(follow ~ ., data = train)
summary(tree1)

cv.m <- cv.tree(tree1, FUN=prune.misclass)
par(mfrow=c(1,2))
plot(cv.m$size ,cv.m$dev ,type="b")
plot(cv.m$k ,cv.m$dev ,type="b")
prune.m = prune.misclass(tree1 ,best=2)


# classification trees
summary(tree1) # the training error is 5%
class.pred <- predict(tree1, test, type="class")
confusionMatrix(class.pred, test$follow)

#pruned tree
tree.pred = predict(prune.m, test, type="class")
confusionMatrix(tree.pred, test$follow)


roc.curve(test$follow, class.pred)
roc.curve(test$follow, tree.pred)
```


```{r}
library("e1071")
svm.ploy <- svm(follow~., kernel = "polynomial", data = train)
summary(svm.ploy)
svm.lm <- svm(follow~., kernel = "linear", data = train)
summary(svm.lm)
svm.rad <- svm(follow~., kernel = "radial", data = train)
summary(svm.rad)
```

```{r}
# svm
library("e1071")
svm.ploy <- svm(follow~., kernel = "polynomial", data = train)

svm.lm <- svm(follow~., kernel = "linear", data = train)

svm.rad <- svm(follow~., kernel = "radial", data = train)


pred_svm.ploy = predict(svm.ploy, test)
table(as.factor(testdata$follow), pred_svm.ploy)

pred_svm.lm = predict(svm.lm, test)
table(as.factor(testdata$follow), pred_svm.lm)

pred_svm.rad= predict(svm.rad, test)
table(as.factor(testdata$follow), pred_svm.rad)

roc.curve(test$follow, pred_svm.ploy)
roc.curve(test$follow, pred_svm.lm)
roc.curve(test$follow, pred_svm.rad)
```


```{r}
# hist(sali$Pct_Persons_Below_Poverty,sali$SEER_Registry)
# 
# p <- sali %>%
#   ggplot(aes(x=Median_Household_Income, fill=Insurance)) +
#     geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
#     labs(fill="")
# 
# p
# 
# 
# 
# sali %>%
#   ggplot(aes(x=follow, fill=Race)) +
#     geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
#     labs(fill="")
```